#!/usr/bin/env python3
"""
*** DATED ANALYSIS SCRIPT — NOT FOR PRODUCTION ***

Committed so the docs/BACKTEST.md §22 baseline extension (Jul-2026) is
reproducible from the repo, NOT as part of any production pipeline. Its output
(single_coin_panel_merged.csv) is a dated analysis artifact and must not be
wired into panel generation, the nightly export, or live sizing — the
production panel is regenerated by scripts/generate_single_coin_panel.py
(Binance source). This script hardcodes the 2026-04-04 seam and a local Drive
scratchpad path specific to the Jul-2026 audit; it is not parameterized for
reuse and will need edits (dates, paths) to re-run against a different window.

Build single_coin_panel_merged.csv WITHOUT overwriting the CoinGecko reference.

The local single_coin_panel.csv (CoinGecko-sourced) is the validation reference
and stops at 2026-04-04 (CoinGecko historical feed died). This script keeps that
core intact and splices Binance USD-M 1d closes onto BOTH ends:

  - FRONT backfill 2024-03-17 .. 2024-04-03  (un-clips the 2024-05-01 cohort's
    45d formation window, which the local panel starts too late to cover).
  - TAIL          2026-04-05 .. 2026-07-13   (extension harvest for the new
    2026-01 / 2026-02 cohorts). funding_rate_8h_decimal and is_perp_active for
    the tail come from the fresh (but price-less) Drive panel copy; close comes
    from Binance.

Output columns match the panel schema. market_cap_usd / rank / open_interest
are left null on the Binance-sourced rows (the Apathy Bleed backtest does not
consume them). The 2026-04-04/05 CoinGecko->Binance seam is a documented
data-source boundary; the perp-vs-spot wedge (0.15-0.30 for low-vol alts) is
handled downstream by the seam-continuity splice check, not here.
"""
from __future__ import annotations

import sys
import time
from datetime import date, datetime, timedelta, timezone
from pathlib import Path

import numpy as np
import pandas as pd
import requests

BINANCE_FAPI = "https://fapi.binance.com"
CORE_PANEL = Path("single_coin_panel.csv")
OUT_PANEL = Path("single_coin_panel_merged.csv")
FRONT_START = date(2024, 3, 17)
FRONT_END = date(2024, 4, 3)
TAIL_START = date(2026, 4, 5)
TAIL_END = date(2026, 7, 13)

sys.path.insert(0, "scripts")
from apathy_bleed_backtest import is_valid_ticker  # reuse universe filter


def _ms(d: date) -> int:
    return int(datetime(d.year, d.month, d.day, tzinfo=timezone.utc).timestamp() * 1000)


def build_symbol_map() -> dict[str, str]:
    r = requests.get(f"{BINANCE_FAPI}/fapi/v1/exchangeInfo", timeout=60,
                     proxies={"http": None, "https": None})
    r.raise_for_status()
    base_to_sym: dict[str, str] = {}
    for s in r.json().get("symbols", []):
        if s.get("contractType") != "PERPETUAL" or s.get("quoteAsset") != "USDT":
            continue
        base = (s.get("baseAsset") or "").upper()
        sym = s.get("symbol")
        if base and sym:
            base_to_sym.setdefault(base, sym)
    return base_to_sym


def resolve_symbol(ticker: str, base_to_sym: dict[str, str]) -> str | None:
    t = ticker.upper()
    for cand in (t, "1000" + t, "1000000" + t, "1M" + t):
        if cand in base_to_sym:
            return base_to_sym[cand]
    return None


def fetch_closes(symbol: str, start_d: date, end_d: date) -> dict[date, float]:
    out: dict[date, float] = {}
    r = requests.get(f"{BINANCE_FAPI}/fapi/v1/klines", timeout=30,
                     proxies={"http": None, "https": None},
                     params={"symbol": symbol, "interval": "1d",
                             "startTime": _ms(start_d), "endTime": _ms(end_d + timedelta(days=1)),
                             "limit": 1500})
    if r.status_code != 200:
        return out
    for k in r.json():
        dd = datetime.fromtimestamp(int(k[0]) / 1000.0, tz=timezone.utc).date()
        try:
            out[dd] = float(k[4])
        except (TypeError, ValueError):
            continue
    return out


def main() -> None:
    core = pd.read_csv(CORE_PANEL)
    core["decision_date_utc"] = pd.to_datetime(core["decision_date_utc"]).dt.strftime("%Y-%m-%d")
    tickers = sorted(core["ticker"].astype(str).str.upper().unique())
    fetch_set = [t for t in tickers if is_valid_ticker(t) or t == "BTC"]
    print(f"core rows={len(core)}, tickers={len(tickers)}, fetching Binance closes for {len(fetch_set)}")

    # Drive panel (price-less but fresh funding / is_perp_active) for the tail.
    drive = pd.read_csv(Path(
        "C:/Users/Admin/AppData/Local/Temp/claude/C--Users-Admin-Documents-Cursor/"
        "7a2ae075-32e7-4e3c-9a30-9284a5653845/scratchpad/drive_panel.csv"))
    drive["decision_date_utc"] = pd.to_datetime(drive["decision_date_utc"]).dt.strftime("%Y-%m-%d")
    drive["ticker"] = drive["ticker"].astype(str).str.upper()

    base_to_sym = build_symbol_map()
    front_rows: list[dict] = []
    tail_rows: list[dict] = []
    misses: list[str] = []

    for i, t in enumerate(fetch_set, 1):
        sym = resolve_symbol(t, base_to_sym)
        if not sym:
            misses.append(t)
            continue
        closes = fetch_closes(sym, FRONT_START, TAIL_END)
        time.sleep(0.08)
        if i % 25 == 0:
            print(f"  [{i}/{len(fetch_set)}] {t}->{sym} ({len(closes)} closes)")
        # FRONT: close only (formation selection); is_perp_active proxied to 1 where priced.
        for d, px in closes.items():
            if FRONT_START <= d <= FRONT_END:
                front_rows.append({"decision_date_utc": d.strftime("%Y-%m-%d"), "ticker": t,
                                   "market_cap_rank": np.nan, "market_cap_usd": np.nan,
                                   "close_price_usd": px, "is_perp_active": 1,
                                   "funding_rate_8h_decimal": np.nan, "open_interest_usd": np.nan})
        # TAIL: close from Binance; funding / is_perp_active from Drive panel.
        for d, px in closes.items():
            if TAIL_START <= d <= TAIL_END:
                ds = d.strftime("%Y-%m-%d")
                drow = drive[(drive["ticker"] == t) & (drive["decision_date_utc"] == ds)]
                if not drow.empty:
                    ipa = int(drow["is_perp_active"].iloc[0]) if pd.notna(drow["is_perp_active"].iloc[0]) else 1
                    fr = drow["funding_rate_8h_decimal"].iloc[0]
                else:
                    ipa, fr = 1, np.nan
                tail_rows.append({"decision_date_utc": ds, "ticker": t,
                                  "market_cap_rank": np.nan, "market_cap_usd": np.nan,
                                  "close_price_usd": px, "is_perp_active": ipa,
                                  "funding_rate_8h_decimal": fr, "open_interest_usd": np.nan})

    merged = pd.concat([pd.DataFrame(front_rows), core, pd.DataFrame(tail_rows)], ignore_index=True)
    merged["decision_date_utc"] = pd.to_datetime(merged["decision_date_utc"])
    merged = merged.sort_values(["ticker", "decision_date_utc"]).reset_index(drop=True)
    merged["decision_date_utc"] = merged["decision_date_utc"].dt.strftime("%Y-%m-%d")
    merged.to_csv(OUT_PANEL, index=False)

    print(f"\nWROTE {OUT_PANEL}: {len(merged)} rows "
          f"(front={len(front_rows)}, core={len(core)}, tail={len(tail_rows)})")
    print(f"date range: {merged['decision_date_utc'].min()} .. {merged['decision_date_utc'].max()}")
    if misses:
        print(f"[WARN] no Binance symbol for {len(misses)}: {misses}")


if __name__ == "__main__":
    main()
