import argparse
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from scipy import stats


def run_regression(timeseries_path: Path, output_path: Path) -> None:
    # Load timeseries
    df = pd.read_csv(timeseries_path)

    # Ensure required columns exist
    if "F_tk" not in df.columns or "y" not in df.columns:
        raise ValueError("Input CSV must contain 'F_tk' and 'y' columns.")

    # Drop NaNs in F_tk or y
    df = df.dropna(subset=["F_tk", "y"])

    if df.empty:
        raise ValueError("No valid rows after dropping NaNs in F_tk and y.")

    x = df["F_tk"].astype(float).values
    y = df["y"].astype(float).values

    # Run OLS regression using scipy.stats.linregress
    result = stats.linregress(x, y)

    slope = result.slope
    intercept = result.intercept
    r_value = result.rvalue
    p_value = result.pvalue

    r_squared = r_value ** 2

    # Print regression statistics
    print("Funding vs Log Return Spread Regression")
    print("---------------------------------------")
    print(f"Number of observations: {len(x)}")
    print(f"Slope (beta_F): {slope:.6f}")
    print(f"Intercept (alpha): {intercept:.6f}")
    print(f"R-squared: {r_squared:.6f}")
    print(f"P-value: {p_value:.6e}")

    # Scatter plot
    plt.figure(figsize=(8, 6))
    plt.scatter(x, y, alpha=0.6, label="Weekly observations")

    # Line of best fit
    x_grid = np.linspace(x.min(), x.max(), 200)
    y_fit = intercept + slope * x_grid
    plt.plot(x_grid, y_fit, color="red", linewidth=2, label="OLS fit")

    plt.xlabel("F_tk (Absolute Funding Rate)")
    plt.ylabel("y (Log Return Spread: majors - alts)")
    plt.title("Funding vs Log Return Spread (OLS Regression)")
    plt.legend()
    plt.grid(True, alpha=0.3)

    output_path.parent.mkdir(parents=True, exist_ok=True)
    plt.tight_layout()
    plt.savefig(output_path, dpi=150)
    plt.close()


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Diagnostic regression of y (log return spread) on F_tk (absolute funding rate)."
    )
    parser.add_argument(
        "--timeseries",
        type=Path,
        default=Path("reports/msm_funding_v0") / "msm_timeseries.csv",
        help="Path to msm_timeseries.csv generated by msm_run.",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("reports") / "funding_scatter_regression.png",
        help="Path to save the regression scatter plot with line of best fit.",
    )

    args = parser.parse_args()

    run_regression(args.timeseries, args.output)


if __name__ == "__main__":
    main()

